cities/urls.py
from django.urls import path

from cities import views


app_name = 'cities'

urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.CityCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', views.CityDetailView.as_view(), name='detail_city'),
    path('update/<int:pk>/', views.CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.CityDeleteView.as_view(), name='delete'),

]

trains/urls.py
from django.urls import path

from trains import views


app_name = 'trains'

urlpatterns = [
    # path('', views.home, name='home'),
    path('', views.TrainListView.as_view(), name='home'),
    path('add/', views.TrainCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', views.TrainDetailView.as_view(), name='detail_train'),
    path('update/<int:pk>/', views.TrainUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.TrainDeleteView.as_view(), name='delete'),

]

travel/urls.py
from django.contrib import admin
from django.urls import path, include

from routes import views

urlpatterns = [
    path('salom/', admin.site.urls),
    path('', views.home, name='home'),
    path('find_routes/', views.find_routes, name='find_routes'),
    path('add_route/', views.add_route, name='add_route'),
    path('save_route/', views.save_route, name='save_route'),
    path('list/', views.RouteListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.RouteDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', views.RouteDeleteView.as_view(), name='delete'),
    path('cities/', include('cities.urls', namespace='cities')),
    path('trains/', include('trains.urls', namespace='trains')),
    path('account/', include('account.urls', namespace='account')),
]

trains/models.py
from django.db import models
from django.core.exceptions import ValidationError

from cities.models import City

class Train(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
        verbose_name='Poyezd nomi'
        )
    travel_time = models.PositiveSmallIntegerField(verbose_name="Yo'l vaqti")
    from_city = models.ForeignKey(
        City,
        on_delete=models.CASCADE,
        related_name='from_city_set',
        verbose_name='Qaysi shahardan'
        )
    to_city = models.ForeignKey(
        'cities.City',
        on_delete=models.CASCADE,
        related_name='to_city_set',
        verbose_name='Qaysi shaharga'
        )


    def __str__(self):
        return f"{self.from_city} shahridan {self.to_city} shahriga {self.name} poyezdi"

    class Meta:
        verbose_name = "Poyezd"
        verbose_name_plural = "Poyezdlar"
        ordering = ['travel_time']


    def clean(self):
        if self.from_city == self.to_city:
            raise ValidationError("Shaharlardan birini o'zgartiring!")
        qs = Train.objects.filter(
            from_city=self.from_city,
            to_city=self.to_city,
            travel_time=self.travel_time
        ).exclude(pk=self.pk)
        # Train == self.__class__
        if qs.exists():
            raise ValidationError("Yo'l vaqtini o'zgartiring!")

    
    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

trains/forms.py
from django import forms
from cities.models import City

from trains.models import Train


class TrainForm(forms.ModelForm):
    name = forms.CharField(label='Poyezd nomeri', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Poyezd nomerini kiriting'
    }))
    travel_time = forms.IntegerField(label="Yo'l vaqti", widget=forms.NumberInput(attrs={
        'class': 'form-control', "placeholder": "Yo'l vaqtini kiriting"}))

    from_city = forms.ModelChoiceField(
        label='Qayerdan', queryset=City.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}))

    to_city = forms.ModelChoiceField(
        label='Qayerga', queryset=City.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Train
        fields = ('__all__')

trains/views.py
from django.shortcuts import render
from django.views.generic import (
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    ListView
    )
from django.urls import reverse_lazy, reverse
from django.core.paginator import Paginator
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin


from trains.models import Train
from trains.forms import TrainForm


def home(request, pk=None):
    title = "Poyezd ro'yhati"
    qs = Train.objects.all()
    list = Paginator(qs, 5)
    page_number = request.GET.get('page')
    page_obj = list.get_page(page_number)
    context = {
        "title": title,
        "page_obj": page_obj,
        }
    
    return render(request, 'trains/home.html', context)



class TrainListView(ListView):
    paginate_by = 5
    model = Train
    template_name = 'trains/home.html'



class TrainDetailView(DetailView):
    queryset = Train.objects.all()
    template_name = 'trains/detail.html'



class TrainCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Train
    form_class = TrainForm
    template_name = 'trains/create.html'
    success_url = reverse_lazy('trains:home')
    success_message = "Poyezd muvaffaqqiyatli qo'shildi!"




class TrainUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Train
    form_class = TrainForm     
    template_name = 'trains/update.html'
    success_url = reverse_lazy('trains:home')
    success_message = "Poyezd haqidagi ma'lumotlar muvaffaqqiyatli tahrirlandi!"



class TrainDeleteView(LoginRequiredMixin, DeleteView):
    model = Train
    # template_name = 'trains/delete.html'
    success_url = reverse_lazy('trains:home')


    def get(self, request, *args, **kwargs):
        messages.success(request, "Poyezd muvaffaqqiyatli o'chirildi!")
        return self.delete(request, *args, **kwargs)

trains/templates/trains/create.html
{% extends 'base.html' %}

{% block title %} Shahar qo'shish {% endblock %}

{% block content %}
<h1>Shahar qo'shish</h1>

{% include 'form.html' with button="Saqlash" %}

{% endblock  %}

trains/templates/trains/delete.html
{% extends 'base.html' %}

{% block title %} Shahar o'chirish {% endblock %}

{% block content %}
<h1>Shahar o'chirish</h1>
<p>{{ object }}</p>
{% include 'form.html' with button="O'chirish" %}

{% endblock  %}

trains/templates/trains/detail.html
{% extends 'base.html' %}

{% block title %} Shahar {% endblock %}

{% block content %}
<h1>Shahar:</h1>
<div class="row">
    <div class="col-md">
        <table class="table table-striped">
            <tr>
                <th>Nomer: </th>
                <th>Qayerdan: </th>
                <th>Qayerga: </th>
                <th>Yo'l vaqti: </th>
            </tr>
            <tr>
                <td>{{object.name}}</td>
                <td>{{object.from_city}}</td>
                <td>{{object.to_city}}</td>
                <td>{{object.travel_time}}</td>
            </tr>
        </table>
    </div>
</div>
<div class+"row">
    <div class="col-md">
        <a href="{% url 'trains:home' %}">
            <button type="button" class="btn btn-light">Shaharlar ro'yhatiga qaytish</button>
        </a>
    </div>
</div>
{% endblock  %}

trains/templates/trains/home.html
{% extends 'base.html' %}
{% block title %}Poyezdlar ro'yhati{% endblock %}
{% block content %}
<h1>
    <p align="center">Poyezdlar ro'yhati:</p>
</h1>
<div class="row">
    <div class="col-md-8 mx-auto my-2">
        <table class="table table-striped">
            <tr>
                <th>Nomer: </th>
                <th>Qayerdan: </th>
                <th>Qayerga: </th>
                <th>Yo'l vaqti: </th>
                <th>&nbsp;</th>
                <th>&nbsp;</th>
            </tr>
            {% for object in page_obj %}
                <tr>
                    <td>
                        <a href={% url 'trains:detail_train' object.id %}>{{object.name}}</a>
                    </td>
                    <td>{{object.from_city}}</td>
                    <td>{{object.to_city}}</td>
                    <td>{{object.travel_time}}</td>
                    {% if user.is_authenticated %}
                        <td>
                            <a href={% url 'trains:update' object.id %}>
                                <button type="submit" class="btn btn-primary">Tahrirlash</button>
                            </a>
                        </td>
                        <td>
                            <a href={% url 'trains:delete' object.id %}>
                                <button type="submit" class="btn btn-danger">O'chirish</button>
                            </a>
                        </td>
                    {% else %}
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

<nav aria-label="...">
    <div class="col-md-8 mx-auto">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                </li>
            {% endif %}
            {% for page in page_obj.paginator.page_range %}
            <li class="page-item {% if page == page_obj.number %} active {% endif %}"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
            </li>
            {% endif %}
          </ul>
    </div>
</nav>

{% endblock  %}

trains/templates/trains/update.html
{% extends 'base.html' %}

{% block title %} Poyezd haqidagi ma'lumtolarni o'zgartirish {% endblock %}

{% block content %}
<h1>Poyezd haqidagi ma'lumtolarni o'zgartirish</h1>
{% include 'form.html' with button="O'zgartirish" %}

{% endblock  %}