cities/urls.py
from django.urls import path

from cities import views


app_name = 'cities'

urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.CityCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', views.CityDetailView.as_view(), name='detail_city'),
    path('update/<int:pk>/', views.CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.CityDeleteView.as_view(), name='delete'),

]

travel/urls.py
from django.contrib import admin
from django.urls import path, include

from routes import views

urlpatterns = [
    path('salom/', admin.site.urls),
    path('', views.home, name='home'),
    path('find_routes/', views.find_routes, name='find_routes'),
    path('add_route/', views.add_route, name='add_route'),
    path('save_route/', views.save_route, name='save_route'),
    path('list/', views.RouteListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.RouteDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', views.RouteDeleteView.as_view(), name='delete'),
    path('cities/', include('cities.urls', namespace='cities')),
    path('trains/', include('trains.urls', namespace='trains')),
    path('account/', include('account.urls', namespace='account')),
]

cities/models.py
from django.db import models
from django.urls import reverse


class City(models.Model):
    name = models.CharField(max_length=128, unique=True,)


    def __str__(self):
        return self.name


    class Meta:
        verbose_name = 'Shahar'
        verbose_name_plural = "Shaharlar"
        ordering = ['name']

    
    def get_absolute_url(self):
        return reverse("cities:detail_city", kwargs={"pk": self.pk})
    

cities/forms.py
from django import forms

from cities.models import City


class HtmlForm(forms.Form):
    name = forms.CharField(label="Shahar")


class CityForm(forms.ModelForm):
    name = forms.CharField(label="Shahar:", widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Shahar nomini kiriting"}))

    class Meta:
        model = City
        fields = ('name', )

    def clean_name(self):
        name = self.cleaned_data['name']
        try:
            city = City.objects.get(name=name)
        except:
            city = None
        if city:
            raise forms.ValidationError('Bu shahar allaqachon kiritilgan!')


        return name

cities/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.core.paginator import Paginator
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin


from cities.models import City
from . import forms


def home(request, pk=None):
    title = "Shaharlar ro'yhati"
    if request.method == "POST":
        form = forms.CityForm(request.POST)
        if form.is_valid():
            form.save
    form = forms.CityForm()
    qs = City.objects.all()
    list = Paginator(qs, 5)
    page_number = request.GET.get('page')
    page_obj = list.get_page(page_number)
    context = {
        "title": title,
        "form": form,
        "page_obj": page_obj,
        }
    
    return render(request, 'cities/home.html', context)



class CityDetailView(DetailView):
    queryset = City.objects.all()
    template_name = 'cities/detail.html'



class CityCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = City
    form_class = forms.CityForm
    template_name = 'cities/create.html'
    success_url = reverse_lazy('cities:home')
    success_message = "Shahar muvaffaqqiyatli qo'shildi!"




class CityUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = City
    form_class = forms.CityForm     
    template_name = 'cities/update.html'
    success_url = reverse_lazy('cities:home')
    success_message = "Shahar haqidagi ma'lumotlar muvaffaqqiyatli tahrirlandi!"



class CityDeleteView(LoginRequiredMixin, DeleteView):
    model = City
    # template_name = 'cities/delete.html'
    success_url = reverse_lazy('cities:home')


    def get(self, request, *args, **kwargs):
        messages.success(request, "Shahar muvaffaqqiyatli o'chirildi!")
        return self.delete(request, *args, **kwargs)

cities/templates/cities/create.html
{% extends 'base.html' %}

{% block title %} Shahar qo'shish {% endblock %}

{% block content %}
<h1>Shahar qo'shish</h1>

{% include 'form.html' with button="Saqlash" %}

{% endblock  %}

cities/templates/cities/delete.html
{% extends 'base.html' %}

{% block title %} Shahar o'chirish {% endblock %}

{% block content %}
<h1>Shahar o'chirish</h1>
<p>{{ object }}</p>
{% include 'form.html' with button="O'chirish" %}

{% endblock  %}

cities/templates/cities/detail.html
{% extends 'base.html' %}

{% block title %} Shahar {% endblock %}

{% block content %}
<h1>Shahar:</h1>
<div class="row">
    <div class="col-md">
        <p>Shahar nomi: {{object.name}}</p>
    </div>
</div>
<div class+"row">
    <div class="col-md">
        <a href="{% url 'cities:home' %}">
            <button type="button" class="btn btn-light">Shaharlar ro'yhatiga qaytish</button>
        </a>
    </div>
</div>
{% endblock  %}

cities/templates/cities/home.html
{% extends 'base.html' %}

{% block content %}
<h1>
    <p align="center">Shaharlar ro'yhati:</p>
</h1>
<div class="row">
    <div class="col-md-8 mx-auto my-2">
        <table class="table table-striped">
        {% for object in page_obj %}
            <tr>
                <td>
                    <a href={% url 'cities:detail_city' object.id %}>{{object.name}}</a>
                </td>
                {% if user.is_authenticated %}
                    <td>
                        <a href={% url 'cities:update' object.id %}>
                            <button type="submit" class="btn btn-primary">Tahrirlash</button>
                        </a>
                    </td>
                    <td>
                        <a href={% url 'cities:delete' object.id %}>
                            <button type="submit" class="btn btn-danger">O'chirish</button>
                        </a>
                    </td>
                {% else %}
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                {% endif %}
            </tr>
        {% endfor %}
        </table>
    </div>
</div>

<nav aria-label="...">
    <div class="col-md-8 mx-auto">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                </li>
            {% endif %}
            {% for page in page_obj.paginator.page_range %}
            <li class="page-item {% if page == page_obj.number %} active {% endif %}"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
            </li>
            {% endif %}
          </ul>
    </div>
</nav>

{% if user.is_authenticated %}
<div class="row">
    <div class="col-md-4">
        <form action="{% url 'cities:create' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Saqlash</button>
        </form>
    </div>
</div>
{% endif %}

{% endblock  %}

cities/templates/cities/update.html
{% extends 'base.html' %}

{% block title %} Shahar o'zgartirish {% endblock %}

{% block content %}
<h1>Shahar o'zgartirish</h1>
{% include 'form.html' with button="O'zgartirish" %}

{% endblock  %}