account/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from . import views
from .forms import PwdResetForm, PwdResetConfirmForm, UserLoginForm


app_name = 'account'

urlpatterns = [
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/',
         views.account_activate, name='activate'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('delete_user/', TemplateView.as_view(
        template_name="account/delete_confirm.html"), name='delete_user'),
    path('delete_user_confirm/<int:pk>/', views.delete_user,
         name='delete_user_confirmation'),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset_form.html",
            success_url="password_reset_email_confirm/",
            email_template_name="account/password_reset_email.html",
            form_class=PwdResetForm
        ),
        name='pwdreset',
    ),
    path(
        'password_reset_confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='account/password_reset_confirm.html',
            success_url='password_reset_complete/',
            form_class=PwdResetConfirmForm,
        ),
        name='password_reset_confirm'
    ),
    path(
        'password_reset/password_reset_email_confirm/',
        TemplateView.as_view(template_name='account/reset_status.html'),
        name='password_reset_done',
    ),
    path(
        'password_reset_confirm/Nw/set-password/password_reset_complete/',
        TemplateView.as_view(template_name='account/reset_status.html'),
        name='password_reset_complete'
    ),
    # path("edit/", views.edit_details, name="edit_details"),
]

cities/urls.py
from django.urls import path

from cities import views


app_name = 'cities'

urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.CityCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', views.CityDetailView.as_view(), name='detail_city'),
    path('update/<int:pk>/', views.CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.CityDeleteView.as_view(), name='delete'),

]

travel/urls.py
from django.contrib import admin
from django.urls import path, include

from routes import views

urlpatterns = [
    path('salom/', admin.site.urls),
    path('', views.home, name='home'),
    path('find_routes/', views.find_routes, name='find_routes'),
    path('add_route/', views.add_route, name='add_route'),
    path('save_route/', views.save_route, name='save_route'),
    path('list/', views.RouteListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.RouteDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', views.RouteDeleteView.as_view(), name='delete'),
    path('cities/', include('cities.urls', namespace='cities')),
    path('trains/', include('trains.urls', namespace='trains')),
    path('account/', include('account.urls', namespace='account')),
]

templates/base.html
{% url 'cities:home' as cities_home_url %}
{% url 'cities:create' as cities_create_url %}
{% url 'trains:home' as trains_home_url %}
{% url 'trains:create' as trains_create_url %}
{% url 'list' as routes_list %}
{% url 'detail' as route_detail %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{{title|title}}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark container">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'home' %}">Yo'l_Top</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link {% if request.path == cities_home_url %} active {% endif %}" aria-current="page" href="{% url 'cities:home' %}">Shaharlar</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if request.path == trains_home_url %} active {% endif %}" aria-current="page" href="{% url 'trains:home' %}">Poyezdlar</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link {% if request.path == routes_list %} active {% endif %}" aria-current="page" href="{% url 'list' %}">Marshrutlar</a>
                  </li>
                  {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle {% if request.path == cities_create_url or request.path == trains_create_url %} active {% endif %}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Qo'shish
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item
                          {% if request.path == cities_create_url %} active {% endif %}"
                          href="{% url 'cities:create' %}">Yangi shahar</a></li>
                        <li><a class="dropdown-item
                          {% if request.path == trains_create_url %} active {% endif %}"
                          href="{% url 'trains:create' %}">Yangi poyezd</a></li>
                      </ul>
                    </li>
                  {% else %}
                    <li class="nav-item">
                      <a class="nav-link disabled" aria-current="page" href="">Qo'shish</a>
                    </li>
                  {% endif %}
                  {% if user.is_authenticated %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Akkaunt
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li>
                        <a class="dropdown-item" aria-current="page" href="{% url 'account:logout' %}">Chiqish</a>
                      </li>
                      <li>
                        <a class="dropdown-item" aria-current="page" href="{% url 'account:delete_user' %}">Accountni o'chirish</a>
                      </li>
                    </ul>
                  </li>                       
                  {% else %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Akkaunt
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li class="nav-item">
                        <a class="dropdown-item" aria-current="page" href="{% url 'account:login' %}">Kirish</a>
                      </li>
                      <li class="nav-item">
                        <a class="dropdown-item" aria-current="page" href="{% url 'account:register' %}">Ro'yhatdan o'tish</a>
                      </li>
                    </ul>
                  </li>
                  {% endif %}
                </ul>
                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
         </nav>
          <div class="container">
            <div class="row">
              <div class="col-md-8 mx-auto my-4">
                {% if messages %}
                    {% for message in messages %}
                          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} 
                              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                          {% else %}
                              <div class="alert alert-success alert-dismissible fade show">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                          {% endif %}
                    {% endfor %}
                {% endif %}
              </div>
            </div>
          </div>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        <script type="text/javascript">
          $(document).ready(function() {
            $('.js-example-basic-single').select2();
            $(".js-example-basic-multiple").select2({multiple:true});
            $(".month").select2({multiple:true});
          });
        </script>
    </body>
</html>

    

templates/form.html
<div class="row">
    <div class="col-md-4 mx-auto">
        <form action="{{action}}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">{{ button }}</button>
        </form>
    </div>
</div>

templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>{{name}}</h1>
{% endblock %}

templates/sub_base.html
{% extends "base.html" %}
{% load static %}
{% block stylesheet %}{% static 'account/css/account.css' %}{% endblock %}

{% block content %}
<div class="container">
  <div class="login d-flex align-items-center">
    <div class="col-12 col-md-12 col-lg-12 mx-auto">
      {% block sub_content %}{% endblock %}
    </div>
  </div>
</div>
{% endblock %}